var files_dup =
[
    [ "docs", "dir_49e56c817e5e54854c35e136979f97ca.html", null ],
    [ "AcoustoOptics.h", "AcoustoOptics_8h.html", "AcoustoOptics_8h" ],
    [ "Auxiliary.h", "Auxiliary_8h.html", "Auxiliary_8h" ],
    [ "Compensation.h", "Compensation_8h.html", "Compensation_8h" ],
    [ "ConnectionList.h", "ConnectionList_8h.html", "ConnectionList_8h" ],
    [ "Containers.h", "Containers_8h.html", "Containers_8h" ],
    [ "CS_ETH.h", "CS__ETH_8h.html", null ],
    [ "CS_RS422.h", "CS__RS422_8h.html", null ],
    [ "Diagnostics.h", "Diagnostics_8h.html", "Diagnostics_8h" ],
    [ "FileSystem.h", "FileSystem_8h.html", "FileSystem_8h" ],
    [ "FirmwareUpgrade.h", "FirmwareUpgrade_8h.html", "FirmwareUpgrade_8h" ],
    [ "IBulkTransfer.h", "IBulkTransfer_8h.html", "IBulkTransfer_8h" ],
    [ "IConnectionSettings.h", "IConnectionSettings_8h.html", "IConnectionSettings_8h" ],
    [ "IEventHandler.h", "IEventHandler_8h.html", "IEventHandler_8h" ],
    [ "Image.h", "Image_8h.html", "Image_8h" ],
    [ "ImageOps.h", "ImageOps_8h.html", "ImageOps_8h" ],
    [ "ImageProject.h", "ImageProject_8h.html", "ImageProject_8h" ],
    [ "IMSSystem.h", "IMSSystem_8h.html", "IMSSystem_8h" ],
    [ "IMSTypeDefs.h", "IMSTypeDefs_8h.html", "IMSTypeDefs_8h" ],
    [ "LibVersion.h", "LibVersion_8h.html", "LibVersion_8h" ],
    [ "SignalPath.h", "SignalPath_8h.html", "SignalPath_8h" ],
    [ "SystemFunc.h", "SystemFunc_8h.html", "SystemFunc_8h" ],
    [ "ToneBuffer.h", "ToneBuffer_8h.html", "ToneBuffer_8h" ],
    [ "VCO.h", "VCO_8h.html", "VCO_8h" ],
    [ "WaveShaping.h", "WaveShaping_8h.html", "WaveShaping_8h" ]
];