/*-----------------------------------------------------------------------------
/ Title      : Connection Manager Header Implementation for Cypress USB Connections
/ Project    : Isomet Modular Synthesiser System
/------------------------------------------------------------------------------
/ File       : $URL: http://nutmeg/svn/sw/trunk/09-Isomet/iMS_SDK/API/ConnectionManager/h/CM_CYUSB.h $
/ Author     : $Author: dave $
/ Company    : Isomet (UK) Ltd
/ Created    : 2015-04-09
/ Last update: $Date: 2023-11-24 08:01:48 +0000 (Fri, 24 Nov 2023) $
/ Platform   :
/ Standard   : C++11
/ Revision   : $Rev: 589 $
/------------------------------------------------------------------------------
/ Description:
/------------------------------------------------------------------------------
/ Copyright (c) 2015 Isomet (UK) Ltd. All Rights Reserved.
/------------------------------------------------------------------------------
/ Revisions  :
/ Date        Version  Author  Description
/ 2015-04-09  1.0      dc      Created
/
/----------------------------------------------------------------------------*/

#ifndef IMS_CM_CYUSB_H__
#define IMS_CM_CYUSB_H__

#if defined(_WIN32)

//------------------------------------------------------------------------------
// include 3rd party Device Driver libraries
//
#include "CyAPI.h"

#include "CM_Common.h"

namespace iMS
{
	// This is a concrete class that implements ConnectionManager via CM_Common.
	//	It is used to communicate with underlying hardware that uses the Cypress USB
	//	Device Driver
	class CM_CYUSB : public CM_Common
	{
	public:
		CM_CYUSB();
		~CM_CYUSB();

		const std::string& Ident() const;

		// Implement ConnectionManager Interface
		std::vector<IMSSystem> Discover(const ListBase<std::string>& PortMask);
		void Connect(const std::string&);
		void Disconnect();
		void SetTimeouts(int send_timeout_ms = 500, int rx_timeout_ms = 5000, int free_timeout_ms = 30000, int discover_timeout_ms = 2500);
		bool MemoryDownload(boost::container::deque<std::uint8_t>& arr, std::uint32_t start_addr, int image_index, const std::array<std::uint8_t, 16>& uuid);
		bool MemoryUpload(boost::container::deque<std::uint8_t>& arr, std::uint32_t start_addr, int len, int image_index, const std::array<std::uint8_t, 16>& uuid);
		int MemoryProgress() ;

	private:
		// Make this object non-copyable
		CM_CYUSB(const CM_CYUSB &);
		const CM_CYUSB &operator =(const CM_CYUSB &);

		// Declare a class that stores information generated by the Sender to be used by the Receiver
		class USBContext;

        // RS422 Fast Transfer Characteristics
        struct CYUSB_Policy {
            CYUSB_Policy(uint32_t addr) : addr(addr) {}

            static constexpr int DL_TRANSFER_SIZE = 131072;
            static constexpr int UL_TRANSFER_SIZE = 8192;
            static constexpr int TRANSFER_GRANULARITY = 1024;
            static constexpr int TRANSFER_UNIT    = 1048576; // DMA max

            uint32_t addr;
        };
        using FastTransfer = CM_Common::FastTransfer<CYUSB_Policy>;

		class Impl;
		Impl *mImpl;

		void MessageSender();
		void ResponseReceiver();
		void MemoryTransfer();
		void InterruptReceiver();
	};

}

#endif

#endif
